### ISSUE TITLE
Adjust (decrease) recording level

### ISSUE THREAD

**Issue by LvDaniel** [AntonyCorbett/OnlyR#63]
Is it possible to adjust/decrease recording level within the app and exclusively for OnlyR?
I know that volume level can be adjusted from Control Panel > Sounds > Recording but we're using FreeConferenceCall for the ones that cannot attend the meeting and if we reduce the volume the participants are affected.
During the OnlyR recording the volume is a bit high and I would like to decrease it with few decibels.
I don't know if technically this is possible but I wanted to ask.
Thank you.

**Comment by AntonyCorbett** [comment]
@LvDaniel 

> During the OnlyR recording the volume is a bit high

OnlyR uses unity gain so if it's distorting then the input device recording volume is too high.

**Comment by LvDaniel** [comment]
@AntonyCorbett Thanks, I'll try to set the input a bit low. Distortion happens only during the songs. Hopefully won't impact the voice for the ones which are listen the meeting though the phone.
FreeConferenceCall has an option to adjust the input automatically and this option was enable. I'll try to change it to manual and see how it goes.

**Comment by lazer321** [comment]
Here is my suggestion:

You might want to check and make sure your recording device is set to the audio in from your mixer/amp. If it is set for Stereo Mix, it might be giving you 2 copies of the song audio summed together, one from JWL and the other from your audio in fed by your mixer/amp.

It would be my suggestion to disable Stereo Mix since it can only lead to trouble. You want the computer's audio that goes out to listener and that is recorded to be a copy of the audio coming out of the mixer/amp only.

One way to test for this is to play the song and turn the volume all the way down in the hall. You should be sending and recording silence under those conditions. You want them to hear what those in the hall hear.

**Comment by LvDaniel** [comment]
@AntonyCorbett Thanks for your suggestions. I'm not sure if we use Stereo Mix but I'll check that for sure. On Wednesday I'll be able to check/test this and I'll let you know.

**Comment by LvDaniel** [comment]
@lazer321 I've checked and we're not using Stereo Mix (it's disabled). I've reduced the recording level to 40% and I also unchecked the option "Allow application to take exclusive control of this device" from the recording device Advanced options, as FreeConferenceCall was automatically modifying the volume. Everything is ok now, thanks for your help.
