### ISSUE TITLE
Crashes after recording

### ISSUE THREAD

**Issue by RickMcKay** [AntonyCorbett/OnlyR#69]
For the last few weeks now OnlyR has crashed each time we have pressed the "stop recording" square stop button. Whilst a folder is created containing the month & day are created, no MP3 file exists.

I have uninstalled & reinstalled the software a number of times but get the same issue each time. No error message is displayed, the software simply crashes & disappears

Screenshot of specs attached
![Spec](https://user-images.githubusercontent.com/61477825/75289870-21a25400-5817-11ea-9d2e-7f800b728766.JPG)

**Comment by lazer321** [comment]
@RickMcKay

Hi Rick,

Here are some thoughts... You might want to check the log file. It should be located in the Documents\OnlyR\Logs folder. It might give some insight on what's going on.

Also, if it has only been happening for the last 2 weeks, you might want to consider a system restore to a point before it started happening.

Just some thoughts. I hope they help.

        - Kevin.

**Comment by AntonyCorbett** [comment]
@RickMcKay please would you send the log file - I'd liek to see what is happening.

**Comment by RickMcKay** [comment]
Hi there
Thanks for the replies & apologies for the delay on my part.

I've attached the last log that was taken though I'm not sure how useful this will be. Reason being is it was created 19.01.20 which was the last successful recording made. On all subsequent occasions; 
23 Jan 20
26 Jan 20
28 Jan 20
30 Jan 20 etc
there are no logs created. There are no recordings either, though the folders for the recordings were created as normal. 

[log-20200119.txt](https://github.com/AntonyCorbett/OnlyR/files/4283004/log-20200119.txt)

As it's been a good few weeks & normal updates from Windows are all that have been installed, I would be sceptical about making a system restore. However if this is the only option available then I will have it done.

Thanks again for looking at this!
Rick

**Comment by lazer321** [comment]
@RickMcKay

Hi Rick,

So sorry to hear of your difficulties! From what you've said, it doesn't seem that the log file will shed much light on the situation. Antony might have some thoughts and additional things that you can try.

In the meantime, just so that you are aware, a system restore does more than just uninstall any programs that were installed since the date of restore. You mentioned in your original post that you had uninstalled and reinstalled the OnlyR program. No doubt, because you wanted to make sure there wasn't an issue with data corruption within the program that was causing the program to crash.

Data corruption can also occur in the operating system that can cause programs to crash expectantly. One could uninstall and reinstall the operating system, but a simpler option would be to use a restore point to reset the operating system's data and settings to a point before the trouble began. Of course, an operating system issue is not the only possible cause of an unexpected program crash. But, since it was working at one time, it might be a good idea to rule out operating system data corruption as a potential source of the issue.

Just some thoughts to consider.

                  - Kevin.

**Comment by AntonyCorbett** [comment]
@RickMcKay If there are no logs created this probably means that OnlyR has no write access to the logs folder which may also explain why the MP3 file is not generated. You can test this by opening the OnlyR\Logs folder in Windows Explorer and trying to create a new text file. Make sure you're logged on using the same account that is used for running OnlyR.

**Comment by AntonyCorbett** [comment]
@RickMcKay Closing for now, but please reopen if you have further info.
